### ISSUE TITLE
Final presentation video

### ISSUE THREAD

**Issue by johannes-kk** [johannes-kk/cs205_final_project#14]

**Comment by wfseaton** [comment]
Version here: https://harvard.zoom.us/rec/play/vsJ8frj5_Dk3TNOT4gSDV_V8W9S5fP2s0HIcr_YFyU-2VyYCMQDwMrEVMeX7pSC6FAOUaY0p2jm-ZAyg?continueMode=true&_x_zm_rtaid=8W0OZrLdRE2wA5NR_p_VdQ.1589223788928.9e7cf25e1245af3533cf5caa9aaf254a&_x_zm_rhtaid=387
