### ISSUE TITLE
Tree: Implement `copy` method.

### ISSUE THREAD

**Issue by gpestre** [johannes-kk/cs205_final_project#35]
- [ ] Shallow copy to create a (single) new node with same pointers.
- [ ] Deep copy that recursively copies subtree.

**Comment by johannes-kk** [comment]
@gpestre anything specific for which we expect to need this?

**Comment by gpestre** [comment]
I don't have anything in mind. I thought it might come in handy for a parallelized hyperparameter search, but we can close this for now and if we need it later it shouldn't be too hard to add.
