### ISSUE TITLE
Pass df to tree.fit() rather than constructor

### ISSUE THREAD

**Issue by johannes-kk** [johannes-kk/cs205_final_project#77]
Currently the training `DataFrame` is passed to the `DecisionTree` or `RandomForest` constructor. Most APIs pass train and test data to `.fit(train_x, train_y)`, not to the constructor. Make ours consistent with that.

**Comment by gpestre** [comment]
@johannes-kk see PR #89 
Taking X and y separately is less straightforward because I don't think we have an efficient way of dropping the y column from an existing DataFrame, but feel free to give it a try.

**Comment by johannes-kk** [comment]
No need. Keep it simple to cut down on time. What we have already works.
