### ISSUE TITLE
SeedGenerator seeds are not working

### ISSUE THREAD

**Issue by johannes-kk** [johannes-kk/cs205_final_project#84]
Running the `RandomForest` with `seed = 1337` gives inconsistent results, suggesting something is missing in the `SeedGenerator` implementation.

**Comment by johannes-kk** [comment]
Adding prints after `random_forest.cpp` line 122 shows `data_seed` and `tree_seed` are both consistent when `RandomForest` is initialised with the same `master_seed`.

**Comment by wfseaton** [comment]
Proposal for cause: https://github.com/johannes-kk/cs205_final_project/pull/85#discussion_r422434843
